"""Checks on the committed `data/tools.json`.

`tools.json` is the contract between the offline generator and the runtime, it
ships inside the wheel, and it is regenerated by hand after a basecamp CLI
upgrade. These tests are what should fail if a regeneration produces something
the runtime or the MCP spec won't accept, rather than a client discovering it.
"""

from __future__ import annotations

from typing import Any

import pytest
from mcp.shared.tool_name_validation import validate_tool_name

from basecamp_cli_mcp.server import _load_tool_specs, build_server


@pytest.fixture(scope="module")
def specs() -> list[dict[str, Any]]:
    return _load_tool_specs()


def test_package_data_is_present_and_populated(specs: list[dict[str, Any]]) -> None:
    """Also covers loading via importlib.resources, which packaging changes break."""
    assert len(specs) > 200


def test_every_spec_has_the_fields_the_runner_needs(specs: list[dict[str, Any]]) -> None:
    for spec in specs:
        missing = {"name", "group", "action", "description", "input_schema"} - spec.keys()
        assert not missing, f"{spec.get('name')} is missing {missing}"
        assert spec["description"].strip(), f"{spec['name']} has an empty description"


def test_tool_names_are_unique(specs: list[dict[str, Any]]) -> None:
    names = [s["name"] for s in specs]
    duplicates = {n for n in names if names.count(n) > 1}
    assert not duplicates


def test_tool_names_conform_to_the_mcp_spec(specs: list[dict[str, Any]]) -> None:
    """SEP-986 naming. mcp 2.x warns per offending tool at registration."""
    invalid = [s["name"] for s in specs if not validate_tool_name(s["name"]).is_valid]
    assert not invalid


def test_input_schemas_are_object_schemas(specs: list[dict[str, Any]]) -> None:
    for spec in specs:
        schema = spec["input_schema"]
        assert schema.get("type") == "object", spec["name"]
        assert isinstance(schema.get("properties"), dict), spec["name"]


def test_required_entries_reference_declared_properties(specs: list[dict[str, Any]]) -> None:
    for spec in specs:
        schema = spec["input_schema"]
        dangling = set(schema.get("required") or []) - schema["properties"].keys()
        assert not dangling, f"{spec['name']} requires undeclared {dangling}"


def test_required_positionals_are_required_in_the_schema(
    specs: list[dict[str, Any]]
) -> None:
    """Otherwise the runner raises ValueError on a call the schema said was valid."""
    for spec in specs:
        required = set(spec["input_schema"].get("required") or [])
        for pos in spec.get("positional") or []:
            if pos.get("required"):
                assert pos["name"] in required, f"{spec['name']}: {pos['name']}"


def test_flag_types_are_ones_the_runner_understands(specs: list[dict[str, Any]]) -> None:
    known = {"boolean", "array", "integer", "string"}
    for spec in specs:
        for flag in spec.get("flags") or []:
            assert flag.get("type") in known, f"{spec['name']}: {flag}"


def test_shortcut_actions_are_not_exposed(specs: list[dict[str, Any]]) -> None:
    """The Shortcuts category duplicates real actions and is skipped at generation."""
    names = {s["name"] for s in specs}
    assert not names & {"todo", "done", "card", "comment"}


def test_the_whole_shipped_set_builds_a_server() -> None:
    """Every spec has to survive validation as an MCP tool, not just the sample ones."""
    server = build_server()
    assert server.name == "basecamp"
